// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTracker.API.Data;

#nullable disable

namespace ProjectTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104150349_AddAttendanceSystem")]
    partial class AddAttendanceSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTracker.API.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLate")
                        .HasColumnType("bit");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 7, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            IsLate = true,
                            LateMinutes = 15,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 8, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 5,
                            IsLate = true,
                            LateMinutes = 5,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 8, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 5,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 6,
                            IsLate = false,
                            Shift = "Afternoon",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 6,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 7,
                            IsLate = true,
                            LateMinutes = 10,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 8, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 7,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 9,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Present",
                            TimeIn = new DateTime(2025, 11, 4, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            AttendanceId = 8,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 4,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Absent"
                        },
                        new
                        {
                            AttendanceId = 9,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 8,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Absent"
                        },
                        new
                        {
                            AttendanceId = 10,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 10,
                            IsLate = false,
                            Shift = "Morning",
                            Status = "Absent"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.AttendanceAdmin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminId");

                    b.ToTable("AttendanceAdmins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$XQRdlQ8P9RfHOKVYOz5Wy.vHZe8RrH7pNWEJhGCRdPQ6kV0UqKPXm",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "IT infrastructure projects",
                            Title = "IT Infrastructure"
                        },
                        new
                        {
                            BoardId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Software development projects",
                            Title = "Software Development"
                        },
                        new
                        {
                            BoardId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Security projects",
                            Title = "Security"
                        },
                        new
                        {
                            BoardId = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Cloud migration projects",
                            Title = "Cloud Migration"
                        },
                        new
                        {
                            BoardId = 5,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Network upgrade projects",
                            Title = "Network Upgrade"
                        },
                        new
                        {
                            BoardId = 6,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Database projects",
                            Title = "Database Management"
                        },
                        new
                        {
                            BoardId = 7,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Mobile application projects",
                            Title = "Mobile Apps"
                        },
                        new
                        {
                            BoardId = 8,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "DevOps projects",
                            Title = "DevOps"
                        },
                        new
                        {
                            BoardId = 9,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "AI integration projects",
                            Title = "AI Integration"
                        },
                        new
                        {
                            BoardId = 10,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Help desk system projects",
                            Title = "Help Desk System"
                        },
                        new
                        {
                            BoardId = 11,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Backup and recovery projects",
                            Title = "Backup Solutions"
                        },
                        new
                        {
                            BoardId = 12,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Description = "Hardware refresh projects",
                            Title = "Hardware Refresh"
                        },
                        new
                        {
                            BoardId = 13,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Supply chain projects",
                            Title = "Supply Chain"
                        },
                        new
                        {
                            BoardId = 14,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Warehouse projects",
                            Title = "Warehouse Management"
                        },
                        new
                        {
                            BoardId = 15,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Fleet management projects",
                            Title = "Fleet Management"
                        },
                        new
                        {
                            BoardId = 16,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Inventory control projects",
                            Title = "Inventory Control"
                        },
                        new
                        {
                            BoardId = 17,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Shipping optimization projects",
                            Title = "Shipping Optimization"
                        },
                        new
                        {
                            BoardId = 18,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Vendor relations projects",
                            Title = "Vendor Relations"
                        },
                        new
                        {
                            BoardId = 19,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Route planning projects",
                            Title = "Route Planning"
                        },
                        new
                        {
                            BoardId = 20,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Distribution center projects",
                            Title = "Distribution Center"
                        },
                        new
                        {
                            BoardId = 21,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Description = "Quality control projects",
                            Title = "Quality Control"
                        },
                        new
                        {
                            BoardId = 22,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Digital marketing projects",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            BoardId = 23,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Content creation projects",
                            Title = "Content Creation"
                        },
                        new
                        {
                            BoardId = 24,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Brand strategy projects",
                            Title = "Brand Strategy"
                        },
                        new
                        {
                            BoardId = 25,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Social media projects",
                            Title = "Social Media"
                        },
                        new
                        {
                            BoardId = 26,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Email campaign projects",
                            Title = "Email Campaigns"
                        },
                        new
                        {
                            BoardId = 27,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Events and promotions",
                            Title = "Events & Promotions"
                        },
                        new
                        {
                            BoardId = 28,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Description = "Market research projects",
                            Title = "Market Research"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CardId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ListId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CreatedAt = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migrated legacy servers to new infrastructure",
                            ListId = 3,
                            Position = 0,
                            Status = "Completed",
                            Title = "Server migration completed"
                        },
                        new
                        {
                            CardId = 2,
                            CreatedAt = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upgraded firewall to latest version",
                            ListId = 3,
                            Position = 1,
                            Status = "Completed",
                            Title = "Firewall upgrade finished"
                        },
                        new
                        {
                            CardId = 3,
                            CreatedAt = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New backup system fully operational",
                            ListId = 3,
                            Position = 2,
                            Status = "Completed",
                            Title = "Backup system implemented"
                        },
                        new
                        {
                            CardId = 4,
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VPN infrastructure deployed",
                            ListId = 3,
                            Position = 3,
                            Status = "Completed",
                            Title = "VPN setup complete"
                        },
                        new
                        {
                            CardId = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Infrastructure monitoring tools active",
                            ListId = 3,
                            Position = 4,
                            Status = "Completed",
                            Title = "Monitoring tools deployed"
                        },
                        new
                        {
                            CardId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "All infrastructure documentation current",
                            ListId = 3,
                            Position = 5,
                            Status = "Completed",
                            Title = "Documentation updated"
                        },
                        new
                        {
                            CardId = 7,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configuring load balancers",
                            ListId = 2,
                            Position = 0,
                            Status = "Active",
                            Title = "Load balancer configuration"
                        },
                        new
                        {
                            CardId = 8,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Migrating DNS infrastructure",
                            ListId = 2,
                            Position = 1,
                            Status = "Active",
                            Title = "DNS migration"
                        },
                        new
                        {
                            CardId = 9,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Renewing SSL certificates",
                            ListId = 2,
                            Position = 2,
                            Status = "Active",
                            Title = "SSL certificate renewal"
                        },
                        new
                        {
                            CardId = 10,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expanding storage capacity",
                            ListId = 2,
                            Position = 3,
                            Status = "Active",
                            Title = "Storage expansion"
                        },
                        new
                        {
                            CardId = 11,
                            CreatedAt = new DateTime(2025, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Decommission old servers",
                            DueDate = new DateTime(2025, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListId = 4,
                            Position = 0,
                            Status = "Active",
                            Title = "Legacy system decommission"
                        },
                        new
                        {
                            CardId = 12,
                            CreatedAt = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete security audit",
                            DueDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ListId = 4,
                            Position = 1,
                            Status = "Active",
                            Title = "Security audit"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CardId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CardAttachments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardComments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManagerName = "Jane Doe",
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManagerName = "Mike Johnson",
                            Name = "Logistics"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManagerName = "John Smith",
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("ShiftEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("ShiftStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "john.doe@company.com",
                            EmployeeCode = "EMP001",
                            FullName = "John Doe",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0101",
                            Position = "Software Developer",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "jane.smith@company.com",
                            EmployeeCode = "EMP002",
                            FullName = "Jane Smith",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0102",
                            Position = "Project Manager",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Logistics",
                            Email = "mike.johnson@company.com",
                            EmployeeCode = "EMP003",
                            FullName = "Mike Johnson",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0103",
                            Position = "Warehouse Manager",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Email = "sarah.williams@company.com",
                            EmployeeCode = "EMP004",
                            FullName = "Sarah Williams",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0104",
                            Position = "Marketing Specialist",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 5,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "robert.brown@company.com",
                            EmployeeCode = "EMP005",
                            FullName = "Robert Brown",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0105",
                            Position = "DevOps Engineer",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 6,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Logistics",
                            Email = "emily.davis@company.com",
                            EmployeeCode = "EMP006",
                            FullName = "Emily Davis",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0106",
                            Position = "Logistics Coordinator",
                            Shift = "Afternoon",
                            ShiftEndTime = new TimeSpan(0, 22, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 7,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Email = "david.miller@company.com",
                            EmployeeCode = "EMP007",
                            FullName = "David Miller",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0107",
                            Position = "Content Writer",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 8,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "lisa.anderson@company.com",
                            EmployeeCode = "EMP008",
                            FullName = "Lisa Anderson",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0108",
                            Position = "QA Tester",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 9,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Logistics",
                            Email = "james.wilson@company.com",
                            EmployeeCode = "EMP009",
                            FullName = "James Wilson",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0109",
                            Position = "Delivery Driver",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 14, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            EmployeeId = 10,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Email = "maria.garcia@company.com",
                            EmployeeCode = "EMP010",
                            FullName = "Maria Garcia",
                            HireDate = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PhoneNumber = "555-0110",
                            Position = "Social Media Manager",
                            Shift = "Morning",
                            ShiftEndTime = new TimeSpan(0, 17, 0, 0, 0),
                            ShiftStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ListId");

                    b.HasIndex("BoardId");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            ListId = 1,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            ListId = 2,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            ListId = 3,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 2,
                            Title = "Completed"
                        },
                        new
                        {
                            ListId = 4,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 3,
                            Title = "Overdue"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@company.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$XQRdlQ8P9RfHOKVYOz5Wy.vHZe8RrH7pNWEJhGCRdPQ6kV0UqKPXm",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "jane@company.com",
                            Name = "Jane Doe",
                            PasswordHash = "$2a$11$XQRdlQ8P9RfHOKVYOz5Wy.vHZe8RrH7pNWEJhGCRdPQ6kV0UqKPXm",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "mike@company.com",
                            Name = "Mike Johnson",
                            PasswordHash = "$2a$11$XQRdlQ8P9RfHOKVYOz5Wy.vHZe8RrH7pNWEJhGCRdPQ6kV0UqKPXm",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "john@company.com",
                            Name = "John Smith",
                            PasswordHash = "$2a$11$XQRdlQ8P9RfHOKVYOz5Wy.vHZe8RrH7pNWEJhGCRdPQ6kV0UqKPXm",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Attendance", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.AuditLog", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Department", "Department")
                        .WithMany("Boards")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.User", "AssignedTo")
                        .WithMany("AssignedCards")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectTracker.API.Models.List", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("List");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardAttachment", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Card", "Card")
                        .WithMany("Attachments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.API.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardComment", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Board", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Department", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Employee", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.Navigation("AssignedCards");
                });
#pragma warning restore 612, 618
        }
    }
}
