// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTracker.API.Data;

#nullable disable

namespace ProjectTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103100508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTracker.API.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(4326),
                            DepartmentId = 1,
                            Description = "Marketing department project tracking",
                            Title = "Marketing Projects"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CardId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ListId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(8471),
                            Description = "Create promotional posters for company calendar",
                            ListId = 1,
                            Position = 0,
                            Status = "Active",
                            Title = "Design calendar posters"
                        },
                        new
                        {
                            CardId = 2,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(8902),
                            Description = "Launch November marketing campaign",
                            ListId = 2,
                            Position = 0,
                            Status = "Active",
                            Title = "November campaign rollout"
                        },
                        new
                        {
                            CardId = 3,
                            CreatedAt = new DateTime(2025, 10, 27, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(8908),
                            Description = "Complete social media strategy update for Q4",
                            ListId = 3,
                            Position = 0,
                            Status = "Completed",
                            Title = "Social media strategy update"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("CardId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CardAttachments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardComments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 619, DateTimeKind.Utc).AddTicks(5908),
                            ManagerName = "John Smith",
                            Name = "Marketing Department"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 619, DateTimeKind.Utc).AddTicks(6142),
                            ManagerName = "Jane Doe",
                            Name = "IT Department"
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 619, DateTimeKind.Utc).AddTicks(6143),
                            ManagerName = "Mike Johnson",
                            Name = "Sales Department"
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 619, DateTimeKind.Utc).AddTicks(6144),
                            ManagerName = "Sarah Williams",
                            Name = "HR Department"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ListId");

                    b.HasIndex("BoardId");

                    b.ToTable("Lists");

                    b.HasData(
                        new
                        {
                            ListId = 1,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(5999),
                            Position = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            ListId = 2,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(6199),
                            Position = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            ListId = 3,
                            BoardId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(6201),
                            Position = 2,
                            Title = "Completed"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(2199),
                            Email = "admin@company.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$wq3z4LhM9QGhGVZ9YDxzje7HYG5QC5qCvW3BdU5qP5M5zk7LvXvO2",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(2613),
                            DepartmentId = 1,
                            Email = "john@company.com",
                            Name = "John Smith",
                            PasswordHash = "$2a$11$wq3z4LhM9QGhGVZ9YDxzje7HYG5QC5qCvW3BdU5qP5M5zk7LvXvO2",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 11, 3, 10, 5, 7, 620, DateTimeKind.Utc).AddTicks(2617),
                            DepartmentId = 2,
                            Email = "jane@company.com",
                            Name = "Jane Doe",
                            PasswordHash = "$2a$11$wq3z4LhM9QGhGVZ9YDxzje7HYG5QC5qCvW3BdU5qP5M5zk7LvXvO2",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("ProjectTracker.API.Models.AuditLog", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Department", "Department")
                        .WithMany("Boards")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.User", "AssignedTo")
                        .WithMany("AssignedCards")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjectTracker.API.Models.List", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("List");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardAttachment", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Card", "Card")
                        .WithMany("Attachments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.API.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.CardComment", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTracker.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Board", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.HasOne("ProjectTracker.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Board", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Card", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.Department", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.List", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ProjectTracker.API.Models.User", b =>
                {
                    b.Navigation("AssignedCards");
                });
#pragma warning restore 612, 618
        }
    }
}
