-- =============================================
-- Seed: Email Accounts
-- Date: March 20, 2026
-- =============================================

USE ProjectTrackerDB;
GO

-- Create table if not exists
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='EmailAccounts' AND xtype='U')
BEGIN
    CREATE TABLE EmailAccounts (
        EmailAccountId INT IDENTITY(1,1) PRIMARY KEY,
        Email NVARCHAR(255) NOT NULL,
        Password NVARCHAR(500) NOT NULL,
        DisplayName NVARCHAR(100) NULL,
        Department NVARCHAR(255) NULL,
        IsActive BIT NOT NULL DEFAULT 1,
        CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
        UpdatedAt DATETIME2 NULL
    );
    CREATE UNIQUE INDEX IX_EmailAccounts_Email ON EmailAccounts(Email);
    PRINT 'Created EmailAccounts table';
END
ELSE
BEGIN
    PRINT 'EmailAccounts table already exists';
    DELETE FROM EmailAccounts;
    PRINT 'Cleared existing data for re-seed';
END
GO

INSERT INTO EmailAccounts (Email, Password, IsActive, CreatedAt) VALUES
('mpume@promedtechnologies.co.za', 'rr#0ebza[@Cs', 1, GETUTCDATE()),
('mandy@promedtechnologies.co.za', '+tMKkId#Es37', 1, GETUTCDATE()),
('sales7@promedtechnologies.co.za', 'D{+0}Qq-Zd0b', 1, GETUTCDATE()),
('info@promedtechnologies.co.za', 'Xwaw%}Ro~0i$', 1, GETUTCDATE()),
('wendy@promedtechnologies.co.za', 'U[@MS^sS_HS4', 1, GETUTCDATE()),
('aldrisha@promedtechnologies.co.za', 'H2RZwUA?(ipl', 1, GETUTCDATE()),
('pe@promedtechnologies.co.za', 'cp;Fu@BIJ+5k', 1, GETUTCDATE()),
('maksooda@promedtechnologies.co.za', 'w1}vaa%C$%~X', 1, GETUTCDATE()),
('trisha@promedtechnologies.co.za', '3V1Ph2HGzvfU', 1, GETUTCDATE()),
('nonhle@promedtechnologies.co.za', '#*jW*x!3fkRH', 1, GETUTCDATE()),
('khothatso@promedtechnologies.co.za', '92)%}C9@$rTv', 1, GETUTCDATE()),
('ayesha@promedtechnologies.co.za', 'C8]aA=#Of5Si', 1, GETUTCDATE()),
('zondi@promedtechnologies.co.za', 'm]iNiNl5*7dY', 1, GETUTCDATE()),
('marketing@promedtechnologies.co.za', 'RsvA$U}CMm~9', 1, GETUTCDATE()),
('sales3@promedtechnologies.co.za', 'Vnhb~K!Mv6cY', 1, GETUTCDATE()),
('emeline@promedtechnologies.co.za', 'bdIp6n^71OuI', 1, GETUTCDATE()),
('gp@promedtechnologies.co.za', 'Ha?LbUHG!0%z', 1, GETUTCDATE()),
('sales2@promedtechnologies.co.za', '#HyuY&x)On6@', 1, GETUTCDATE()),
('graphics@promedtechnologies.co.za', 'KDZU;X41XX1k', 1, GETUTCDATE()),
('cpt@promedtechnologies.co.za', '4HRS[nhOuaIi', 1, GETUTCDATE()),
('yoliswa@promedtechnologies.co.za', 'B3GqM41u-j0c', 1, GETUTCDATE()),
('siya@promedtechnologies.co.za', '&=@3bMsrV1FT', 1, GETUTCDATE()),
('masiya@promedtechnologies.co.za', 'c&&W]G#gQ+Yn', 1, GETUTCDATE()),
('akhona@promedtechnologies.co.za', 'jFh~&p![.^H2', 1, GETUTCDATE()),
('farnaaz@promedtechnologies.co.za', '8}Qx0(q5O$tN', 1, GETUTCDATE()),
('orders@promedtechnologies.co.za', 'v[Cz0t_%p4_w', 1, GETUTCDATE()),
('lindani@promedtechnologies.co.za', '[xT?!9.*&Nn7', 1, GETUTCDATE()),
('masixole@promedtechnologies.co.za', 'up5YY!_arJY[', 1, GETUTCDATE()),
('jane@promedtechnologies.co.za', '-]STE$kir2&E', 1, GETUTCDATE()),
('mpilo@promedtechnologies.co.za', '%N)nnj$UmI?%', 1, GETUTCDATE()),
('ryan@promedtechnologies.co.za', 'J!t?dAte[]y#', 1, GETUTCDATE()),
('dbn1@promedtechnologies.co.za', 'Po{)pW^EVYhe', 1, GETUTCDATE()),
('sales8@promedtechnologies.co.za', 'KTVGxT-VBpUC', 1, GETUTCDATE()),
('dbn2@promedtechnologies.co.za', '{D@P3xikJ0%,', 1, GETUTCDATE()),
('gp2@promedtechnologies.co.za', 'iab{mJQ2XJ[6', 1, GETUTCDATE()),
('swelihle@promedtechnologies.co.za', '+{Ak8b(otKi!', 1, GETUTCDATE()),
('precious@promedtechnologies.co.za', 'd(M.7ymSMCT8', 1, GETUTCDATE()),
('welcome@promedtechnologies.co.za', '6!d+4=S.8d#O', 1, GETUTCDATE()),
('candice@promedtechnologies.co.za', 'g4FE0F=,eH?i', 1, GETUTCDATE()),
('arren@promedtechnologies.co.za', '4VlGKvm%jYr)', 1, GETUTCDATE()),
('pods1@promedtechnologies.co.za', 'p!8S.?DVV-l?', 1, GETUTCDATE()),
('abbigail@promedtechnologies.co.za', 'T14?l39o-%rE', 1, GETUTCDATE()),
('nasiphi@promedtechnologies.co.za', '!SCh*mP*VM7l', 1, GETUTCDATE()),
('accounts3@promedtechnologies.co.za', '%fY6Qw.{%of=', 1, GETUTCDATE()),
('mpolokeng@promedtechnologies.co.za', '{oH%3e&,;F,9', 1, GETUTCDATE()),
('imports@promedtechnologies.co.za', 'cq5#YN@m95u#', 1, GETUTCDATE()),
('lungile1@promedtechnologies.co.za', 'Ty1hW^Ba.St.', 1, GETUTCDATE()),
('pearl@promedtechnologies.co.za', '=KRQZv8gC+.E', 1, GETUTCDATE()),
('commissions@promedtechnologies.co.za', 'ccM[G]?&97Nb', 1, GETUTCDATE()),
('logistics2@promedtechnologies.co.za', 'WixV]VVWz7o6', 1, GETUTCDATE()),
('hlengiwe@promedtechnologies.co.za', '1%+W)xlnCIoW', 1, GETUTCDATE()),
('stock@promedtechnologies.co.za', 'AM1=aR4-d_x&', 1, GETUTCDATE()),
('dylan@promedtechnologies.co.za', 'xNFgkwYwvYya', 1, GETUTCDATE()),
('pods@promedtechnologies.co.za', '4v6$!J@gMTNh', 1, GETUTCDATE()),
('sphindile@promedtechnologies.co.za', 'd@qC]q$$#g5R', 1, GETUTCDATE()),
('samira@promedtechnologies.co.za', '$][PQ5dym!Jn', 1, GETUTCDATE()),
('deon@promedtechnologies.co.za', '5eOzifC}nZDc', 1, GETUTCDATE()),
('accounts7@promedtechnologies.co.za', '4RUal(+O8)(k', 1, GETUTCDATE()),
('masi@promedtechnologies.co.za', 'eM;,8fhCvRI7', 1, GETUTCDATE()),
('nomfundo@promedtechnologies.co.za', '.lmw~U?7?Wsu', 1, GETUTCDATE()),
('procurement@promedtechnologies.co.za', 'pZEjzeTYgCh-', 1, GETUTCDATE()),
('norel@promedtechnologies.co.za', '~#aG{9#?ohX%', 1, GETUTCDATE()),
('accounts8@promedtechnologies.co.za', 'OD[?pc.AQd4s', 1, GETUTCDATE()),
('hafeeza@promedtechnologies.co.za', 'yuN8@QgH!za$', 1, GETUTCDATE()),
('reception@promedtechnologies.co.za', 'tiu5otE(G[na', 1, GETUTCDATE()),
('hr2@promedtechnologies.co.za', 'T!K4ymrbiK)G', 1, GETUTCDATE()),
('accounts9@promedtechnologies.co.za', '^@%JYqR;B$bt', 1, GETUTCDATE()),
('logistics1@promedtechnologies.co.za', 'ZxX4f^qD9~Sp', 1, GETUTCDATE()),
('jennifer@promedtechnologies.co.za', '%gX0w~xZ4^Hk', 1, GETUTCDATE()),
('seelan@promedtechnologies.co.za', 'e(=[{Z=^i;MU', 1, GETUTCDATE()),
('lenisha@promedtechnologies.co.za', 'dw83Fds}XR2_', 1, GETUTCDATE()),
('sales4@promedtechnologies.co.za', '8p_fQn~9-kxU', 1, GETUTCDATE()),
('lungile@promedtechnologies.co.za', 'P,sS%f)zvdoF', 1, GETUTCDATE()),
('adithi@promedtechnologies.co.za', '0g+?,cJh$4ho', 1, GETUTCDATE()),
('thathokuhle@promedtechnologies.co.za', 'T2Y8](_ddS]7', 1, GETUTCDATE()),
('sales1@promedtechnologies.co.za', 'nb{rJAa9!U-#', 1, GETUTCDATE()),
('logistics4@promedtechnologies.co.za', '2q]uQkpHwD$S', 1, GETUTCDATE()),
('donavan@promedtechnologies.co.za', 'WRhd;ToEwuAv', 1, GETUTCDATE()),
('accounts1@promedtechnologies.co.za', '#8htai1eYb}G', 1, GETUTCDATE()),
('sales5@promedtechnologies.co.za', 't%Vb9{}reqgk', 1, GETUTCDATE()),
('strini@promedtechnologies.co.za', 'ImFAC%H@PH0n', 1, GETUTCDATE()),
('zinhle@promedtechnologies.co.za', '6g(Tbp,{j2Z)', 1, GETUTCDATE()),
('logisticsmanager@promedtechnologies.co.za', 'k)cks1CQNH=.', 1, GETUTCDATE()),
('it@promedtechnologies.co.za', '7A?hX#1lItY-', 1, GETUTCDATE()),
('sales6@promedtechnologies.co.za', '{cDT4qj={qb,', 1, GETUTCDATE()),
('zeenat@promedtechnologies.co.za', 'F455BX,AhFc~', 1, GETUTCDATE()),
('accountant@promedtechnologies.co.za', '=JCwH^7r8pZ;', 1, GETUTCDATE()),
('veli@promedtechnologies.co.za', 'jCWlfoA^R1TP', 1, GETUTCDATE()),
('duran@promedtechnologies.co.za', '-ZNN@$^z$H@X', 1, GETUTCDATE()),
('treasury@promedtechnologies.co.za', 'oDx=qSQsRc=E', 1, GETUTCDATE()),
('denisha@promedtechnologies.co.za', '^uGScpbY9fLA', 1, GETUTCDATE()),
('banele@promedtechnologies.co.za', 'l;mHxv$+]T&G', 1, GETUTCDATE()),
('shantal@promedtechnologies.co.za', 'Q9t(paQ[Wl7?', 1, GETUTCDATE()),
('nandipha@promedtechnologies.co.za', '32KScOk~g]7d', 1, GETUTCDATE()),
('hr@promedtechnologies.co.za', '5S4zWisJ7boY', 1, GETUTCDATE()),
('anisha@promedtechnologies.co.za', '90)Ct)%5}L!2', 1, GETUTCDATE()),
('accounts10@promedtechnologies.co.za', 'izczi9p;,@?R', 1, GETUTCDATE()),
('keith@promedtechnologies.co.za', '[ijE_!hvP7CX', 1, GETUTCDATE()),
('kavashnee@promedtechnologies.co.za', 'sOghy#W%3wTM', 1, GETUTCDATE()),
('production1@promedtechnologies.co.za', 'q]{*9+1P.,H!', 1, GETUTCDATE()),
('accounts4@promedtechnologies.co.za', 'jRtvYE{jFZ}1', 1, GETUTCDATE()),
('sayushka@promedtechnologies.co.za', 'jJ=P?xMGR{hn', 1, GETUTCDATE()),
('logistics9@promedtechnologies.co.za', ')[BjgasE)E7,', 1, GETUTCDATE()),
('selby@promedtechnologies.co.za', 'gWEvZ$KT*ta4', 1, GETUTCDATE()),
('chanel@promedtechnologies.co.za', 'Q-^V_^hyt+1a', 1, GETUTCDATE()),
('ashveer@promedtechnologies.co.za', '*UYQZPqNni5z', 1, GETUTCDATE()),
('production@promedtechnologies.co.za', 'Sd~QW1w2w8X?', 1, GETUTCDATE()),
('pvtsales@promedtechnologies.co.za', '8kZ7H3S;Sp7J', 1, GETUTCDATE()),
('nonhlanhla@promedtechnologies.co.za', 'OvEfg9^tT]?X', 1, GETUTCDATE()),
('nondumiso@promedtechnologies.co.za', '0WMItLe=Vo,=', 1, GETUTCDATE()),
('similo@promedtechnologies.co.za', 'wl.FyU;e,0Nh', 1, GETUTCDATE()),
('nombali@promedtechnologies.co.za', 'pelO&%H0+p9y', 1, GETUTCDATE()),
('orders1@promedtechnologies.co.za', '[UsxL7~,4;aY', 1, GETUTCDATE()),
('nondu@promedtechnologies.co.za', 'z)-hJktU$qMD', 1, GETUTCDATE()),
('laptop@promedtechnologies.co.za', 'F-*x)OqXRKt1', 1, GETUTCDATE()),
('logistics5@promedtechnologies.co.za', 'UC=23o80}Q#~', 1, GETUTCDATE()),
('boardroom@promedtechnologies.co.za', 'miJ#_z%@#E#%', 1, GETUTCDATE()),
('chenell@promedtechnologies.co.za', '^bh#?Ol1pZ85', 1, GETUTCDATE()),
('velosha@promedtechnologies.co.za', '6_KIG6t7scC3', 1, GETUTCDATE()),
('verusha@promedtechnologies.co.za', '.c8W1.@0?;V5', 1, GETUTCDATE()),
('mzamo@promedtechnologies.co.za', 'R3l5j4!5]kzZ', 1, GETUTCDATE()),
('diabetes@promedtechnologies.co.za', '@??4mm2e6?{h', 1, GETUTCDATE()),
('admin@promedtechnologies.co.za', '}S=u-!U8RL,i', 1, GETUTCDATE()),
('mbalenhle@promedtechnologies.co.za', 'rXOssL,5H8fK', 1, GETUTCDATE()),
('keegan@promedtechnologies.co.za', 'BhfWOv_;QxkP', 1, GETUTCDATE()),
('logistics3@promedtechnologies.co.za', '3e..kTA5rb7V', 1, GETUTCDATE()),
('logistics7@promedtechnologies.co.za', ')cBHnFy.!y^r', 1, GETUTCDATE()),
('ntando@promedtechnologies.co.za', '+vUClH7]u0oz', 1, GETUTCDATE()),
('mbali@promedtechnologies.co.za', '^PzY[wRbdDJ3', 1, GETUTCDATE()),
('support@promedtechnologies.co.za', '_Q9P{d=G@dEw', 1, GETUTCDATE()),
('salescomputer@promedtechnologies.co.za', 'wZ_Tji4#sX)}', 1, GETUTCDATE()),
('newsletter@promedtechnologies.co.za', 'ZJn*h+RFwcej', 1, GETUTCDATE()),
('condoms@promedtechnologies.co.za', 'R.8d4*!zoQdd', 1, GETUTCDATE()),
('accounts2@promedtechnologies.co.za', 'y~(YVYwx#[rO', 1, GETUTCDATE()),
('portia@promedtechnologies.co.za', 'wEaSUg2KkR~W', 1, GETUTCDATE()),
('kuben@promedtechnologies.co.za', '7&Jty~8Bi+g[', 1, GETUTCDATE()),
('priya@promedtechnologies.co.za', 'kq72*cP)S$8=', 1, GETUTCDATE()),
('nicolla@promedtechnologies.co.za', 'W%J8nO#zn2&$', 1, GETUTCDATE()),
('phindile@promedtechnologies.co.za', 'c=}%P6ph$L;c', 1, GETUTCDATE()),
('accounts5@promedtechnologies.co.za', 'evb1Na&xw-iP', 1, GETUTCDATE()),
('hr3@promedtechnologies.co.za', '5;bj}2#?5Bw1', 1, GETUTCDATE()),
('logistics8@promedtechnologies.co.za', '5EsX$4HJ5Ozk', 1, GETUTCDATE()),
('artworks@promedtechnologies.co.za', '5@wq#QaOM&-&', 1, GETUTCDATE()),
('it2@promedtechnologies.co.za', 'aMMVSBU7?}}*', 1, GETUTCDATE()),
('finance@promedtechnologies.co.za', '+hdMw3Ll.mSv', 1, GETUTCDATE()),
('siboniso@promedtechnologies.co.za', '9h)0OSV[0u&W', 1, GETUTCDATE()),
('pule@promedtechnologies.co.za', 'QIRL28NA=~b(', 1, GETUTCDATE()),
('sydneyn@promedtechnologies.co.za', 'tu~7}fi68vh=', 1, GETUTCDATE()),
('avirthar@promedtechnologies.co.za', 'jMb,nqmik(+B', 1, GETUTCDATE()),
('export@promedtechnologies.co.za', 'gB%vJU+}KJr5', 1, GETUTCDATE()),
('logistics6@promedtechnologies.co.za', '+$b4tzZ8(6yS', 1, GETUTCDATE()),
('crm@promedtechnologies.co.za', 'FA.I4z.%2sQq', 1, GETUTCDATE()),
('poct@promedtechnologies.co.za', '7tyGpdbyH~pW', 1, GETUTCDATE()),
('probot@promedtechnologies.co.za', 'wFg7wlysA?gX', 1, GETUTCDATE()),
('progpt@promedtechnologies.co.za', 'gBuT+#o#T]i,', 1, GETUTCDATE()),
('sage@promedtechnologies.co.za', ']]n{l{4,)8KX', 1, GETUTCDATE()),
('jenniferk@promedtechnologies.co.za', 'lrczIx@!DqL', 1, GETUTCDATE()),
('accounts6@promedtechnologies.co.za', '14_%%]Yu_T[{', 1, GETUTCDATE());
GO

-- Verify
SELECT 'Total Email Accounts' AS Label, COUNT(*) AS Count FROM EmailAccounts;
GO
