-- Seed Employees SQL Script
-- Default password hash for "Welcome123!" generated by BCrypt
DECLARE @DefaultPasswordHash NVARCHAR(MAX) = '$2a$11$K8rBpQqKEGLEJVfcnqxQNO.aJQxpfQxqK6v1s7J2L1aHRKmqOjMVC';

-- Step 1: Ensure Departments exist
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Reception')
    INSERT INTO Departments (Name) VALUES ('Reception');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Accounts')
    INSERT INTO Departments (Name) VALUES ('Accounts');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Sales')
    INSERT INTO Departments (Name) VALUES ('Sales');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Stock')
    INSERT INTO Departments (Name) VALUES ('Stock');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Logistics')
    INSERT INTO Departments (Name) VALUES ('Logistics');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Production')
    INSERT INTO Departments (Name) VALUES ('Production');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Marketing')
    INSERT INTO Departments (Name) VALUES ('Marketing');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Finance')
    INSERT INTO Departments (Name) VALUES ('Finance');
IF NOT EXISTS (SELECT 1 FROM Departments WHERE Name = 'Training')
    INSERT INTO Departments (Name) VALUES ('Training');

-- Step 2: Ensure Operating Companies exist
IF NOT EXISTS (SELECT 1 FROM OperatingCompanies WHERE Code = 'ACCESS')
    INSERT INTO OperatingCompanies (Name, Code, Description, IsActive) VALUES ('Access Medical', 'ACCESS', 'Access Medical supplies and equipment', 1);
IF NOT EXISTS (SELECT 1 FROM OperatingCompanies WHERE Code = 'PROMED')
    INSERT INTO OperatingCompanies (Name, Code, Description, IsActive) VALUES ('Promed Technologies', 'PROMED', 'Promed Technologies healthcare solutions', 1);
IF NOT EXISTS (SELECT 1 FROM OperatingCompanies WHERE Code = 'PHARMA')
    INSERT INTO OperatingCompanies (Name, Code, Description, IsActive) VALUES ('Promed Pharmacare', 'PHARMA', 'Promed Pharmacare pharmaceutical products', 1);
IF NOT EXISTS (SELECT 1 FROM OperatingCompanies WHERE Code = 'SEBENZANI')
    INSERT INTO OperatingCompanies (Name, Code, Description, IsActive) VALUES ('Sebenzani Trading', 'SEBENZANI', 'Sebenzani Trading distribution', 1);
IF NOT EXISTS (SELECT 1 FROM OperatingCompanies WHERE Code = 'SAWELLNESS')
    INSERT INTO OperatingCompanies (Name, Code, Description, IsActive) VALUES ('SA Wellness', 'SAWELLNESS', 'SA Wellness health and wellness', 1);

-- Create temp table for employee data
CREATE TABLE #EmployeeData (
    Name NVARCHAR(100),
    Surname NVARCHAR(100),
    Email NVARCHAR(255),
    Title NVARCHAR(100),
    Department NVARCHAR(100),
    Ext1 NVARCHAR(20),
    Ext2 NVARCHAR(20),
    Ext3 NVARCHAR(20),
    Ext4 NVARCHAR(20),
    Company1 NVARCHAR(20),
    Company2 NVARCHAR(20)
);

-- Insert employee data
INSERT INTO #EmployeeData VALUES ('Reception', 'Desk', 'reception@accessmedical.co.za', 'Receptionist', 'Reception', '100', '200', '300', '700', 'ACCESS', 'PROMED');
INSERT INTO #EmployeeData VALUES ('Ashveer', '', 'ashveer@promedtechnologies.co.za', 'Staff', 'Sales', '102', NULL, NULL, NULL, 'PROMED', 'PHARMA');
INSERT INTO #EmployeeData VALUES ('Velosha', '', 'orders@promedtechnologies.co.za', 'Orders', 'Sales', '703', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Shanice', '', 'stock@promedpharmacare.co.za', 'Stock Controller', 'Stock', '103', NULL, NULL, NULL, 'PHARMA', NULL);
INSERT INTO #EmployeeData VALUES ('Mamo', '', 'acconts11@promedtechnologies.co.za', 'Accounts', 'Accounts', '104', NULL, NULL, NULL, 'PROMED', 'ACCESS');
INSERT INTO #EmployeeData VALUES ('Nhlonipho', '', 'accounts1@promedtechnologies.co.za', 'Accounts', 'Accounts', '105', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nduduzo', '', 'accounts5@promedtechnologies.co.za', 'Accounts', 'Accounts', '107', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Karishma', '', 'production1@promedpharmare.co.za', 'Production', 'Production', '108', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Calvin', '', 'marketing@promedtechnologie.co.za', 'Marketing', 'Marketing', '109', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Norel', '', 'norel@accessmedical.co.za', 'Staff', 'Sales', '110', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Xoli', '', 'logistics1@promedtechnologies.co.za', 'Logistics', 'Logistics', '111', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Abby', '', 'abbigail@promedtechnologies.co.za', 'Staff', 'Sales', '112', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Karusha', '', 'karusha@promedtechnologies.co.za', 'Staff', 'Sales', '113', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Buancha', '', 'buancha@promedtechnologies.co.za', 'Staff', 'Sales', '114', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Deon', '', 'logistics3@promedtechnologies.co.za', 'Logistics', 'Logistics', '115', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Coleen', '', 'coleen@promedtechnologies.co.za', 'Accounts', 'Accounts', '116', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Anesh', '', 'logistics2@promedtechnologies.co.za', 'Logistics', 'Logistics', '117', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Jennifer', 'Stock', 'stock@accessmedical.co.za', 'Stock Controller', 'Stock', '118', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Mbali', 'Finance', 'accounts10@promedtechnologies.co.za', 'Finance', 'Finance', '201', NULL, NULL, NULL, 'ACCESS', 'PROMED');
INSERT INTO #EmployeeData VALUES ('Mandy', '', 'mandy@accessmedical.co.za', 'Staff', 'Sales', '707', NULL, NULL, NULL, 'ACCESS', 'PROMED');
INSERT INTO #EmployeeData VALUES ('Ahistar', '', 'sales1@promedpharmacare.co.za', 'Sales', 'Sales', '203', NULL, NULL, NULL, 'ACCESS', 'SEBENZANI');
INSERT INTO #EmployeeData VALUES ('Maksooda', '', 'maksooda@promedtechnologies.co.za', 'Staff', 'Sales', '206', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nash', '', 'nash22.govender@gmail.com', 'Staff', 'Sales', '911', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Duran', '', 'duran24govender@gmail.com', 'Staff', 'Sales', '666', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Jerwayne', '', 'jerwaynegovender@gmail.com', 'Staff', 'Sales', NULL, NULL, NULL, NULL, 'SEBENZANI', NULL);
INSERT INTO #EmployeeData VALUES ('Kajal', '', 'acconts2@accessmedical.co.za', 'Accounts', 'Accounts', '205', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Noori', '', 'accounts8@promedtechnologies.co.za', 'Accounts', 'Accounts', '207', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Hlengiwe', '', 'hlengiwe@promedtechnologies.co.za', 'Staff', 'Sales', '208', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Mpilo', '', 'mpilo@promedtechnologies.co.za', 'Staff', 'Sales', '210', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Pearl', '', 'pearl@accessmedical.co.za', 'Staff', 'Sales', '209', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Thando', '', 'ryan@promedtechnologies.co.za', 'Staff', 'Sales', '212', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Sisanda', '', 'stock1@sebenzanitrading.com', 'Stock Controller', 'Stock', '301', NULL, NULL, NULL, 'ACCESS', 'PHARMA');
INSERT INTO #EmployeeData VALUES ('Mabaso', '', 'wonder@sawellness.prop.sa', 'Staff', 'Sales', '302', NULL, NULL, NULL, 'SAWELLNESS', NULL);
INSERT INTO #EmployeeData VALUES ('Jennifer', '', 'jennifer@accessmedical.co.za', 'Staff', 'Sales', '303', NULL, NULL, NULL, 'ACCESS', 'PROMED');
INSERT INTO #EmployeeData VALUES ('Sydney', '', 'stock@promedtechnologies.co.za', 'Stock Controller', 'Stock', '304', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Vinola', '', 'accounts7@promedtechnologies.co.za', 'Accounts', 'Accounts', '305', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Joyce', '', 'sales1@accessmedical.co.za', 'Sales', 'Sales', '704', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Maggie', '', 'maggie@promedtechnologies.co.za', 'Staff', 'Sales', '705', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Trisha', '', 'trisha@promedechnologies.co.za', 'Staff', 'Sales', '401', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Sphindile', '', 'sphindile@promedtechnologies.co.za', 'Staff', 'Sales', '404', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nomvelo', '', 'sales2@promedtechnologies.co.za', 'Sales', 'Sales', '714', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Thabile', '', 'thabile@promedtechnologies.co.za', 'Staff', 'Sales', '403', NULL, NULL, NULL, 'PROMED', 'ACCESS');
INSERT INTO #EmployeeData VALUES ('Mpume', '', 'sales3@promedtechnologies.co.za', 'Sales', 'Sales', '706', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nelly', '', 'sales2@accessmedical.co.za', 'Sales', 'Sales', '710', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Anisha', '', 'anisha@promedtechnologies.co.za', 'Staff', 'Sales', '409', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Akhona', '', 'akhona@promedtechnologies.co.za', 'Staff', 'Sales', '701', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Aldrisha', '', 'aldrisha@promedtechnologies.co.za', 'Staff', 'Sales', '708', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nkosikhona', '', 'sales7@promedtechnologies.co.za', 'Sales', 'Sales', '712', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Swelihle', '', 'swelihle@promedtechnologies.co.za', 'Staff', 'Sales', '713', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Keith', '', 'sales1@promedtechnologies.co.za', 'Sales', 'Sales', '715', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nkosikhona', 'B', 'sales10@promedtechnologies.co.za', 'Sales', 'Sales', '716', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Nosipho', '', 'sales16@promedtechnologies.co.za', 'Sales', 'Sales', '718', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Sthabile', '', 'sales5@accessmedical.co.za', 'Sales', 'Sales', '725', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Emeline', '', 'sales4@promedtechnologies.co.za', 'Sales', 'Sales', '726', NULL, NULL, NULL, 'SEBENZANI', NULL);
INSERT INTO #EmployeeData VALUES ('Mandisa', '', 'sales11@promedtechnologies.co.za', 'Sales', 'Sales', '728', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Vuyiswa', '', 'sales3@sebenzanitrading.com', 'Sales', 'Sales', '724', NULL, NULL, NULL, 'SEBENZANI', NULL);
INSERT INTO #EmployeeData VALUES ('Zandile', 'Msomi', 'sales1@sebenzanitrading.com', 'Sales', 'Sales', '730', NULL, NULL, NULL, 'SEBENZANI', NULL);
INSERT INTO #EmployeeData VALUES ('Zandile', 'Mkhize', 'sales9@promedtechnologies.co.za', 'Sales', 'Sales', '729', NULL, NULL, NULL, 'SEBENZANI', NULL);
INSERT INTO #EmployeeData VALUES ('Cynthia', '', 'sales8@accessmedical.co.za', 'Sales', 'Sales', '702', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Thabsile', '', 'thabsile@accessmedical.co.za', 'Staff', 'Sales', '727', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Hlaka', '', 'training@promedtechnlogies.co.za', 'Training', 'Training', '722', NULL, NULL, NULL, 'PROMED', NULL);
INSERT INTO #EmployeeData VALUES ('Pinky', '', 'sales4@accessmedical.co.za', 'Sales', 'Sales', '721', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Smangele', '', 'sales3@accessmedical.co.za', 'Sales', 'Sales', '732', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Amanda', '', 'sales10@accessmedical.co.za', 'Sales', 'Sales', '709', NULL, NULL, NULL, 'ACCESS', NULL);
INSERT INTO #EmployeeData VALUES ('Lisa', '', 'sales6@promedtechnologies.co.za', 'Sales', 'Sales', '731', NULL, NULL, NULL, 'ACCESS', NULL);

-- Step 3: Insert Users
INSERT INTO Users (Name, Surname, Email, PasswordHash, Role, Title, DepartmentId, IsActive, CreatedAt)
SELECT 
    e.Name,
    ISNULL(e.Surname, ''),
    e.Email,
    @DefaultPasswordHash,
    'Employee',
    e.Title,
    (SELECT TOP 1 DepartmentId FROM Departments WHERE Name = e.Department),
    1,
    GETUTCDATE()
FROM #EmployeeData e
WHERE NOT EXISTS (SELECT 1 FROM Users u WHERE u.Email = e.Email);

PRINT 'Users inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Step 4: Insert Extensions and link to users
INSERT INTO Extensions (ExtensionNumber, Label, ExtensionType, UserId, IsActive, IsPrimary, CreatedAt)
SELECT 
    e.Ext1,
    'Direct Line',
    'Phone',
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    1,
    1,
    GETUTCDATE()
FROM #EmployeeData e
WHERE e.Ext1 IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM Extensions WHERE ExtensionNumber = e.Ext1);

PRINT 'Extensions (Ext1) inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Insert Ext2 extensions
INSERT INTO Extensions (ExtensionNumber, Label, ExtensionType, UserId, IsActive, IsPrimary, CreatedAt)
SELECT 
    e.Ext2,
    'Direct Line',
    'Phone',
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    1,
    0,
    GETUTCDATE()
FROM #EmployeeData e
WHERE e.Ext2 IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM Extensions WHERE ExtensionNumber = e.Ext2);

PRINT 'Extensions (Ext2) inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Insert Ext3 extensions
INSERT INTO Extensions (ExtensionNumber, Label, ExtensionType, UserId, IsActive, IsPrimary, CreatedAt)
SELECT 
    e.Ext3,
    'Direct Line',
    'Phone',
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    1,
    0,
    GETUTCDATE()
FROM #EmployeeData e
WHERE e.Ext3 IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM Extensions WHERE ExtensionNumber = e.Ext3);

PRINT 'Extensions (Ext3) inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Insert Ext4 extensions
INSERT INTO Extensions (ExtensionNumber, Label, ExtensionType, UserId, IsActive, IsPrimary, CreatedAt)
SELECT 
    e.Ext4,
    'Direct Line',
    'Phone',
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    1,
    0,
    GETUTCDATE()
FROM #EmployeeData e
WHERE e.Ext4 IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM Extensions WHERE ExtensionNumber = e.Ext4);

PRINT 'Extensions (Ext4) inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Step 5: Link Users to Operating Companies (Primary)
INSERT INTO StaffOperatingCompanies (StaffMemberId, OperatingCompanyId, IsPrimaryCompany, IsActive)
SELECT 
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    (SELECT TOP 1 OperatingCompanyId FROM OperatingCompanies WHERE Code = e.Company1),
    1,
    1
FROM #EmployeeData e
WHERE e.Company1 IS NOT NULL
AND EXISTS (SELECT 1 FROM Users WHERE Email = e.Email)
AND NOT EXISTS (
    SELECT 1 FROM StaffOperatingCompanies soc 
    WHERE soc.StaffMemberId = (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email)
    AND soc.OperatingCompanyId = (SELECT TOP 1 OperatingCompanyId FROM OperatingCompanies WHERE Code = e.Company1)
);

PRINT 'Primary company links inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Link Users to Operating Companies (Secondary)
INSERT INTO StaffOperatingCompanies (StaffMemberId, OperatingCompanyId, IsPrimaryCompany, IsActive)
SELECT 
    (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email),
    (SELECT TOP 1 OperatingCompanyId FROM OperatingCompanies WHERE Code = e.Company2),
    0,
    1
FROM #EmployeeData e
WHERE e.Company2 IS NOT NULL
AND EXISTS (SELECT 1 FROM Users WHERE Email = e.Email)
AND NOT EXISTS (
    SELECT 1 FROM StaffOperatingCompanies soc 
    WHERE soc.StaffMemberId = (SELECT TOP 1 UserId FROM Users WHERE Email = e.Email)
    AND soc.OperatingCompanyId = (SELECT TOP 1 OperatingCompanyId FROM OperatingCompanies WHERE Code = e.Company2)
);

PRINT 'Secondary company links inserted: ' + CAST(@@ROWCOUNT AS VARCHAR(10));

-- Cleanup temp table
DROP TABLE #EmployeeData;

-- Final counts
SELECT 
    (SELECT COUNT(*) FROM Users) AS TotalUsers,
    (SELECT COUNT(*) FROM Extensions) AS TotalExtensions,
    (SELECT COUNT(*) FROM StaffOperatingCompanies) AS TotalCompanyLinks,
    (SELECT COUNT(*) FROM OperatingCompanies) AS TotalCompanies,
    (SELECT COUNT(*) FROM Departments) AS TotalDepartments;

PRINT 'Employee seeding complete!';
